# Generated by Django 3.2.6 on 2021-08-16 09:41

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('code', models.CharField(choices=[('EE 201', 'EE 201'), ('EE 203', 'EE 203'), ('EE 205', 'EE 205'), ('EE 253', 'EE 253'), ('MA 203', 'MA 203'), ('IC 211', 'IC 211')], max_length=10)),
                ('day', multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
    ]
